WITH
    sales_calc
    AS
    (
        SELECT
            [KNDNR] KNDNR,
            -- [KUNWE] KUNWE,
            [BUKRS] BUKRS,
            [MANDT] MANDT,
            [BUDAT] BUDAT,
            [MATKL] MATKL,
            [VVQ01_ME] VVQ01_ME,
            [VVR13] VVR13,
            [WWRCP] WWRCP,
            [ARTNR] ARTNR,
            [WWI06] WWI06,
            [WWI04] WWI04,
            [VKORG] VKORG,
            [PERDE] PERDE,
            [WADAT] WADAT,
            [FADAT] FADAT,
            [RPOSN] RPOSN,
            [KAUFN] KAUFN,
            [VVQ13] VVQ13,
            [VVQ01] VVQ01,
            [VVR93] VVR93,
            [VVR92] VVR92,
            [VVR89] VVR89,
            [VVR70] VVR70,
            [PRODH] PRODH,
            ((ISNULL([VVR98],0)+ISNULL([VVR99],0)+ISNULL([VVR95],0)+ISNULL([VVRR2],0)+ISNULL([VVR03],0)+ISNULL([VVR94],0)+ISNULL([VVR88],0)+ISNULL([VVRR1],0))-(ISNULL([VVR93],0)+ISNULL([VVR92],0)+ISNULL([VVR89],0)+ISNULL([VVR70],0))) AS sales
        FROM [APAC_DATA_REPO].[dbo].[PEA_CE10COC]
        WHERE [LAND1] ='AU'
            AND CAST([BUDAT] AS DATETIME) < '2021-01-01'
            AND CAST([BUDAT] AS DATETIME) >= '2019-01-01'
            AND [PALEDGER] = 2
            AND [AUART] NOT LIKE '0CT%'
    )

SELECT
    'PEA'+[MANDT]+'.'+[BUKRS]+'.'+ [KNDNR] AS 'CUSTOMER_NUMBER',
    '0' AS 'SHIP_TO',
    COUNT(DISTINCT [ARTNR]) AS 'CNTD_MATERIAL',
    COUNT(DISTINCT [MATKL]) AS 'MATERIAL_GROUP',
    MAX([WWI06]) AS 'INDUSTRY',
    MAX([WWI04]) AS 'INDUSTRY_SUBLEVEL',
    MAX([VKORG]) AS 'PLANT',
    MAX([PERDE]) AS 'POSTING_PERIOD',
    DATEDIFF(day, MIN([BUDAT]), MAX([BUDAT])) AS 'DAY_BETWEEN_POSTING',
    FORMAT([BUDAT], 'yyyy-MM') 'POSTING_DATE',
    COUNT(DISTINCT CASE WHEN [VVQ01_ME] in ('CMO','CDA') THEN [BUDAT] END) as 'CNTD_RENTAL_POSTING_DATE',
    COUNT(DISTINCT [BUDAT]) 'CNTD_POSTING_DATE',
    COUNT([BUDAT]) 'CNT_POSTING_DATE',
    AVG(DATEDIFF(D,[WADAT],[FADAT])) 'AVG_DOCUMENT_ISSUE_DIFF',
    AVG(DATEDIFF(D,[BUDAT],[FADAT])) 'AVG_POST_ISSUE_DIFF',
    COUNT(DISTINCT [RPOSN]) 'REFERENCE_ITEMS',
    COUNT(DISTINCT [KAUFN]) AS 'ORDER_NO',
    SUM(CASE WHEN [VVQ01_ME] = 'CDA' THEN ISNULL([VVQ13],0) ELSE 0 END) AS 'CCH',
    SUM(CASE WHEN [VVQ01_ME] <> 'CMO' AND [VVQ01_ME] <> 'CDA' THEN ISNULL([VVQ13],0) ELSE 0 END) AS 'SALE_QTY',
    SUM(CASE WHEN [VVQ01_ME] in ('CMO','CDA') THEN ISNULL([VVQ01],0) END) AS 'RENTAL_BILLED_QTY',
    SUM(CASE WHEN [VVQ01_ME] <> 'CMO' AND [VVQ01_ME] <> 'CDA' THEN sales END) AS 'PRODUCT_SALES',
    SUM(CASE WHEN [VVQ01_ME] in ('CMO','CDA') THEN sales END) AS 'RENTAL_SALES',
    SUM(CASE WHEN [VVQ01_ME] <> 'CMO' AND [VVQ01_ME] <> 'CDA' THEN [VVR13] END) 'DELIVERY',
    COUNT(CASE WHEN [WWRCP] like 'D' THEN 1 END) 'DAILY_RENT',
    COUNT(CASE WHEN [WWRCP] = 'M' THEN 1 END) 'MONTHLY_RENT',
    COUNT(CASE WHEN [WWRCP] = 'Q' THEN 1 END) 'QUARTERLY_RENT',
    COUNT(CASE WHEN [WWRCP] = 'A' THEN 1 END) 'ANNUAL_RENT',
    COUNT(CASE WHEN [WWRCP] not in ('A','D','M','Q') THEN 1 END) 'Other_Rent_Period',
    ROUND(SUM(CASE WHEN sales = 0 THEN 0 ELSE (ISNULL([VVR93],0)+ISNULL([VVR92],0)+ISNULL([VVR89],0)+ISNULL([VVR70],0))/sales END), 3) AS 'DISCOUNT_RATIO',
    SUM(CASE WHEN [MATKL] = '02-01-12' THEN sales END) AS 'MATERIAL_020112_SALE',
    SUM(CASE WHEN [MATKL] = '05-02-99' THEN sales END) AS 'MATERIAL_050299_SALE',
    SUM(CASE WHEN [MATKL] = '02-01-10' THEN sales END) AS 'MATERIAL_020110_SALE',
    SUM(CASE WHEN [MATKL] = '02-01-04' THEN sales END) AS 'MATERIAL_020104_SALE',
    SUM(CASE WHEN [MATKL] = '11-18-99' THEN sales END) AS 'MATERIAL_111899_SALE',
    SUM(CASE WHEN MATKL = '05-12-99' THEN sales END) AS 'MATERIAL_051299_SALE',
    SUM(CASE WHEN PRODH = 'CO10500001LRGLG' THEN sales END) AS 'PROD_LRGLG_SALE',
    SUM(CASE WHEN PRODH = 'CO10500001SMLLD2' THEN sales END) AS 'PROD_SMLLD2_SALE',
    SUM(CASE WHEN PRODH = 'CO10500001MEDLE' THEN sales END) AS 'PROD_1MEDLE_SALE',
    SUM(CASE WHEN PRODH = 'CD10010015SMLLD' THEN sales END) AS 'PROD_SMLLD_SALE',
    SUM(CASE WHEN PRODH = 'CD10010015MEDLE' THEN sales END) AS 'PROD_5MEDLE_SALE',
    SUM(CASE WHEN PRODH = 'CA50100024MEDLE2' THEN sales END) AS 'PROD_4MEDLE2_SALE',
    SUM(CASE WHEN PRODH = 'CA50100028LRGLG' THEN sales END) AS 'PROD_8LRGLG_SALE'
FROM sales_calc
GROUP BY [KNDNR],[MANDT],[BUKRS], FORMAT([BUDAT], 'yyyy-MM') --[KUNWE]
